name: build-blocknetx
run-name: build-blocknetx
on: [push]

env: 
  BASEPREFIX: depends
  BASEPREFIX_CACHE: depends-cache
  DISTDIR: dist

jobs:
  build-db4:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: install general deps
        run: |
          sudo apt update
          sudo apt install -y \
            software-properties-common \
            ca-certificates \
            wget curl git python vim \
            gcc g++ binutils
      - name: install essential deps
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            build-essential libtool autotools-dev bsdmainutils \
            libevent-dev autoconf automake pkg-config libssl-dev \
            python-setuptools cmake libcap-dev
      - uses: actions/cache@v3
        id: cache-db4
        env:
          cache-name: libdb4
        with:
          path: ./db4/
          key: ${{ runner.os }}-build-${{ env.cache-name }}
      - name: compile libdb4.8
        if: ${{ steps.cache-db4.outputs.cache-hit != 'true' }}
        run: ./contrib/install_db4.sh .

  build-blocknet:
    runs-on: ubuntu-20.04
    needs: build-db4
    steps:
      - uses: actions/checkout@v3
      - name: install general deps
        run: |
          sudo apt update
          sudo apt install -y \
            software-properties-common \
            ca-certificates \
            wget curl git python vim \
            gcc g++ binutils
      - name: install essential deps
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            build-essential libtool autotools-dev bsdmainutils \
            libevent-dev autoconf automake pkg-config libssl-dev \
            python-setuptools cmake libcap-dev
      - name: install libboost deps
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            libssl-dev \
            libevent-dev \
            libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev
      - name: install extra deps
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            libminiupnpc-dev \
            libzmq3-dev \
            libqrencode-dev
      - name: install qt deps
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            libqt5gui5 libqt5core5a libqt5dbus5 \
            qttools5-dev qttools5-dev-tools \
            libprotobuf-dev protobuf-compiler
      - uses: actions/cache@v3
        env:
          cache-name: libdb4
        with:
          path: ./db4/
          key: ${{ runner.os }}-build-${{ env.cache-name }}
      - name: run autogen
        run: |
          chmod +x ./autogen.sh; sync
          ./autogen.sh
      - name: run configure
        run: |
          ./configure \
            BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I/${BDB_PREFIX}/include" \
            --disable-tests --disable-bench --enable-cxx --disable-shared --with-pic 
        env:
          PROJECTDIR: ${{ github.workspace }}
          BDB_PREFIX: ${{ github.workspace }}/db4
          BASEPREFIX: ${{ github.workspace }}/depends
          DISTDIR: ${{ github.workspace }}/dist
