name: build-blocknetx
run-name: build-blocknetx
on: [push]

env: 
  BASEPREFIX: depends
  BASEPREFIX_CACHE: depends-cache
  DISTDIR: dist

jobs:
  build-db4:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: install general deps
        run: |
          sudo apt update
          sudo apt install -y \
            software-properties-common \
            ca-certificates \
            wget curl git python vim \
            gcc g++ binutils
      - name: install essential deps
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            build-essential libtool autotools-dev bsdmainutils \
            libevent-dev autoconf automake pkg-config libssl-dev \
            python-setuptools cmake libcap-dev
      - name: compile libdb4.8
        run: ./contrib/install_db4.sh .
      - name: archive compiled libdb4.8
        run: tar czf libdb4.tar.gz db4/  
      - uses: actions/upload-artifact@v3
        with:
          name: libdb4
          path: ./libdb4.tar.gz
          if-no-files-found: error

  build-blocknet:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: install general deps
        run: |
          sudo apt update
          sudo apt install -y \
            software-properties-common \
            ca-certificates \
            wget curl git python vim \
            gcc g++ binutils
      - name: install essential deps
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            build-essential libtool autotools-dev bsdmainutils \
            libevent-dev autoconf automake pkg-config libssl-dev \
            python-setuptools cmake libcap-dev
      - name: install libboost deps
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            libssl-dev \
            libevent-dev \
            libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev
      - name: install extra deps
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            libminiupnpc-dev \
            libzmq3-dev \
            libqrencode-dev
      - name: install qt deps
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            libqt5gui5 libqt5core5a libqt5dbus5 \
            qttools5-dev qttools5-dev-tools \
            libprotobuf-dev protobuf-compiler
      - uses: actions/download-artifact@master
        with:
          name: libdb4
          path: ./libdb4.tar.gz
      - name: extract bundled libdb4
        run: |
          tar xzvf libdb4.tar.gz
          rm libdb4.tar.gz
      - name: run autogen
        run: |
          chmod +x ./autogen.sh; sync
          ./autogen.sh
      - name: run configure
        run: |
          /configure \
            BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I/${BDB_PREFIX}/include" \
            --disable-tests --disable-bench --enable-cxx --disable-shared --with-pic 
        env:
          PROJECTDIR: ${{ vars.GITHUB_WORKSPACE}}
          BDB_PREFIX: ${{ vars.PROJECTDIR }}/db4
          BASEPREFIX: ${{ vars.PROJECTDIR }}/depends
          DISTDIR: ${{ vars.PROJECTDIR }}/dist
