name: build-blocknetx
run-name: build-blocknetx
on: [push]

env: 
  BASEPREFIX: depends
  BASEPREFIX_CACHE: depends-cache
  DISTDIR: dist

jobs:
  build-blocknet:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: install general deps
        run: |
          sudo apt update && \ 
          sudo apt install -y \
            software-properties-common \
            ca-certificates \
            wget curl git python vim \
            gcc g++ binutils
      - name: install essential deps
        run: |
          sudo apt update &&\
          sudo apt install -y --no-install-recommends \
            build-essential libtool autotools-dev bsdmainutils \
            libevent-dev autoconf automake pkg-config libssl-dev \
            python-setuptools cmake libcap-dev \
            libdb4.8-dev libdb4.8++-dev
      - name: install libboost deps
        run: |
          sudo apt update &&\
          sudo apt install -y --no-install-recommends \
            libssl-dev \
            libevent-dev \
            libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev
      - name: install extra deps
        run: |
          sudo apt update &&\
          sudo apt install -y --no-install-recommends \
            libminiupnpc-dev \
            libzmq3-dev \
            libqrencode-dev
      - name: install qt deps
        run: |
          sudo apt update &&\
          sudo apt install -y --no-install-recommends \
            libqt5gui5 libqt5core5a libqt5dbus5 \
            qttools5-dev qttools5-dev-tools \
            libprotobuf-dev protobuf-compiler
      - name: run autogen
        run: |
          chmod +x ./autogen.sh; sync
          ./autogen.sh